language: node_js
python:
  - "3.6"

services:
  - docker

install: 
  #- pip install coverage
  - docker build -t fiuber-node ./
  - mkdir shared

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - mkdir coverage
  - docker-compose pull
  - docker-compose build
  - docker-compose up --abort-on-container-exit
  #- docker-compose up -d db
  #- docker ps
  #VERSION VIEJA - docker-compose run -v "$PWD/coverage:/app/coverage" $ci_env web sh test-cover-enviar-en-docker.sh
  - docker-compose run -v "$PWD/coverage:/app/coverage" $ci_env web npm run cover
  #- docker ps
  #- docker-compose down
  #- docker ps
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json -t 12e9be3a-0f98-417e-b477-d94f6d07b25e
