language: node_js
python:
  - "3.6"

services:
  - docker

install: 
  - pip install coverage
  - docker build -t fiuber-node ./
  - mkdir shared

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - mkdir coverage
  - docker-compose pull
  - docker-compose build
  - docker-compose up --abort-on-container-exit
  - docker run $ci_env -v "$PWD/shared:/app/shared" -p 5000:5000 app-server sh test-cover-enviar-en-docker-appserver.sh
#  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json -t 9b56dd78-a3ab-4a7d-a7ea-bd326e5348ad
